zetapush/zetapush

- packages/core/src/client/basic.js
- packages/core/src/client/helper.js
- packages/core/test/services/proxy-macro-service.spec.js
- packages/core/test/services/proxy-service.spec.js
affects: @zetapush/core
Use ES2015 Proxies to create generic promise based services
ISSUES CLOSED: #2
> feat(client): add createProxy(Macro)Service to create generic service

- .travis.yml
- package.json
> chore(travis-ci): add Travis CI

- packages/core/src/client/basic.js
- packages/core/src/client/smart.js
- packages/core/test/api-url.spec.js
- packages/core/test/client.spec.js
- packages/core/test/sandbox-alias.spec.js
- packages/core/test/services/async-macro.spec.js
- packages/core/test/services/macro.spec.js
- packages/core/test/services/proxy-macro-service.spec.js
- packages/core/test/services/proxy-service.spec.js
- packages/core/test/weak-client.spec.js
- packages/example/public/file/index.js
- packages/example/public/group/index.js
- packages/example/public/hello-world/index.js
- packages/example/public/user/index.js
- packages/example/public/utils/index.js
- packages/server/src/client/server.js
Support promise based method for connect() and disconnect() methods
affects: @zetapush/cli, @zetapush/core, @zetapush/example, @zetapush/server
ISSUES CLOSED: #1
> feat(async-connection): support promise based method for connect() and disconnect() methods

- packages/cli/bin/cli.js
- packages/cli/bin/commands/push.js
- packages/cli/bin/commands/register.js
- packages/cli/bin/commands/run.js
- packages/cli/bin/utils/bootstrap.js
- packages/cli/bin/utils/config.js
- packages/cli/bin/utils/defaults.js
- packages/cli/bin/utils/provisionning.js
> feat(cli-register): implements register command, rename args

- README.md
- packages/cli/bin/commands/run.js
- packages/cli/bin/loader/config.js
- packages/core/index.d.ts
- packages/core/src/authentication/handshake.js
- packages/core/src/client/basic.js
- packages/core/src/client/helper.js
- packages/core/src/client/smart.js
- packages/core/src/client/weak.js
- packages/core/src/utils/network.js
- packages/core/src/utils/session-persistence.js
- packages/core/test/api-url.spec.js
- packages/core/test/client-error.spec.js
- packages/core/test/client.spec.js
- packages/core/test/fetch.spec.js
- packages/core/test/lifecycle-events.spec.js
- packages/core/test/sandbox-alias.spec.js
- packages/core/test/services/async-macro.spec.js
- packages/core/test/services/macro.spec.js
- packages/core/test/services/proxy-macro-service.spec.js
- packages/core/test/services/proxy-service.spec.js
- packages/core/test/weak-client.spec.js
- packages/create/template/front/index.js
- packages/example/front/index.js
- packages/example/package.json
- packages/worker/src/client/worker.js
affects: @zetapush/cli, @zetapush/core, @zetapush/create, @zetapush/example, @zetapush/worker
sandboxId --> appName
apiUrl --> platformUrl
BREAKING CHANGE:
Change top level api for client options
> feat(api): update top level api with new wording definitions

- package-lock.json
- packages/cli/bin/commands/run.js
- packages/cli/package-lock.json
- packages/cli/package.json
> feat(CLI/run): add progress on the 'zeta run' command with info of end

- Jenkinsfile
- packages/cli/src/errors/network-issue.js
- packages/cli/src/errors/troubleshooting.js
- packages/cli/src/utils/network.js
- packages/integration/package.json
+ add traces for debugging
+ fix github raw url
> fix(IT) Add config in error context for help analysis

- packages/cli/src/errors/access-denied-issue.js
> fix(cli): fix account not validated error

- .github/ISSUE_TEMPLATE.md
ISSUES CLOSED: #63
```
[x] Bugfix
[ ] Feature
```
Template issue has bad reference to @angular package
Template issue has only reference to @zetapush package
```
[ ] Yes
[x] No
```
**Other …
> fix(template-issue): rename Angular to ZetaPush ref, add missing \`\`\`

- .github/ISSUE_TEMPLATE.md
```
[x] Bugfix
[ ] Feature
```
@zetapush is not in bold
@zetapush in in bold
```
[ ] Yes
[x] No
```
> fix(oss): fix typo for template issue

- packages/platform/src/service/Gda.ts
affects: @zetapush/platform
```
[ ] Bugfix
[x] Feature
```
Gda service is not fully typed
Gda service is now fully typed
```
[ ] Yes
[x] No
```
> feat(platform): add typings for Gda service

- packages/worker/src/client/worker.js
affects: @zetapush/worker
```
[ ] Bugfix
[x] Feature
```
The timeout value on a custom cloud service method is 5000ms.
The timeout value on a custom cloud service method is 60000ms.
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please describe the impact and migration path for existing …
> feat(worker): increase worker timeout to 60000ms

- packages/cli/src/commands/push.js
- packages/cli/src/errors/access-denied-issue.js
- packages/cli/src/errors/asciidoc-parser.js
- packages/cli/src/errors/conditions.js
- packages/cli/src/errors/config-load-issue.js
- packages/cli/src/errors/custom-cloud-service-start-issue.js
- packages/cli/src/errors/errors-handler.js
- packages/cli/src/errors/injection-issue.js
- packages/cli/src/errors/network-issue.js
- packages/cli/src/errors/npm-dependency-issue.js
- packages/cli/src/utils/helper-messages.js
- packages/cli/src/utils/http-server.js
- packages/cli/src/utils/network.js
- packages/cli/src/utils/progression.js
- packages/cli/src/utils/upload.js
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[x] No
```
> refactor: clean unused variables, remove request implementation

- packages/create/template/typescript/tsconfig.json
affects: @zetapush/create
ISSUES CLOSED: #75
```
[ ] Bugfix
[x] Feature
```
https://github.com/zetapush/zetapush/issues/75
```
[ ] Yes
[x] No
```
> feat(create): enable sourceMap option by default for TypeScript project

- packages/platform/src/Core/Configurer.ts
- packages/platform/src/Core/Service.ts
- packages/platform/tsconfig.json
affects: @zetapush/platform
```
[ ] Bugfix
[x] Feature
```
Platform package is not transpiled with stricts checks.
Platform package is now transpiled with stricts checks.
```
[ ] Yes
[x] No
``` …
> feat(platform-strict-config): improve TypeScript check for platform package

- packages/cometd/lib/browser/Transports.js
affects: @zetapush/cometd
ISSUES CLOSED: #78
```
[x] Bugfix
[ ] Feature
```
https://github.com/zetapush/zetapush/issues/78
ServiceWorker are now supported
```
[ ] Yes
[x] No
```
**Other …
> fix(cometd): support ServiceWorker execution context

- packages/cli/package-lock.json
- packages/cli/package.json
ISSUES CLOSED: #56
```
[ ] Bugfix
[x] Feature
```
Hot Module Replacement is unstable with VSCode
```
[ ] Yes
[x] No
```
> feat(cli): bump hot-module-replacement version

- packages/client/src/client/helper.js
- packages/example/front/cometd.js
- packages/worker/src/utils/worker-instance.ts
affects: @zetapush/client, @zetapush/example, @zetapush/worker
```
[ ] Bugfix
[x] Feature
```
Error thrown after a server side exception return client side stack trace.
Error thrown after a server side exception contains only code and message.
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please …
> feat(worker): improve error message on error from server

- packages/worker/src/client/worker.ts
affects: @zetapush/worker
```
[ ] Bugfix
[x] Feature
```
Worker instance doesn't respond on configure message
Worker instance respond on configure message with a successfull result
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please describe the impact and migration path for existing applications: …
> feat(configure-compatibility): add a synchronous succcessfull done result for server futurproof comp

- packages/create/template/javascript/worker/index.js
- packages/create/template/typescript/worker/index.ts
affects: @zetapush/create
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
> fix(create): update default example

- packages/worker/src/utils/worker-instance.ts
affects: @zetapush/worker
ISSUES CLOSED: #61
```
[x] Bugfix
[ ] Feature
```
Extra logs are displayed in the console
Extra logs are not displayed in the console
```
[ ] Yes
[x] No
```
**Other …
> fix(log): inject logger in context method object

- packages/example/worker/index.ts
affects: @zetapush/example
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(example): rename context[logLevel] to context.logger[logLevel]

- packages/client/index.d.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(Client): add the 'createProxyTaskService' method in index.d.ts

- packages/client/index.d.ts
- packages/client/src/client/helper.js
```
[X] Bugfix
[ ] Feature
[X] Other... Please describe: The ProxyTaskService returns a Promise of the output instead of the output
```
We can't use the `createProxyTaskService()` method
Now we can create a ProxyTaskService via `createProxyTaskService()`
```
[ ] Yes
[X] No
```
If this PR contains a breaking change, …
> fix(Client): update the 'createProxyTaskService' method

- packages/client/rollup.config.js
- packages/client/src/authentication/handshake.js
- packages/client/src/client/helper.js
```
[x] Bugfix
[ ] Feature
```
Current **@zetapush/client** version is not stable.
**@zetapush/client** version is now stable
```
[ ] Yes
[x] No
```
> fix(fix-build-client): fix build client

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- Jenkinsfile
- packages/client/karma.conf.js
- packages/client/package-lock.json
- packages/client/package.json
- packages/client/test/reports/.gitignore
- packages/user-management/package-lock.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Share vscode configuration
```
```
[ ] Yes
[x] No
```
> chore(vscode): share launch/tasks configuration

- packages/create/template/javascript/worker/index.js
- packages/create/template/typescript/worker/index.ts
- packages/example/worker/index.ts
affects: @zetapush/create, @zetapush/example
```
[ ] Bugfix
[x] Feature
```
Generated template are not up to date with latest practices.
Generated template are up to date with latest practices.
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please describe the impact and migration path for existing …
> feat(create-template-improvement): update created templates with latest practices

- package.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Published canary version are not exact
Published canary version are now exact
```
[ ] Yes
[x] No
```
> chore(publish-exact-canary): update publish script to publish exact versions

- packages/example/worker/index.ts
```
[x] Bugfix
[ ] Feature
```
Project example is not up to date
Project example is up to date
```
[ ] Yes
[x] No
```
> feat(example): update example with latest dependencies

- packages/example/worker/logger.ts
```
[x] Bugfix
[ ] Feature
```
Example contains an error in logger config file
Logger config file example depends of correct packages
```
[ ] Yes
[x] No
```
> fix(example): update logger config example

- packages/user-management/spec/it/standard-user-workflow/core/account/AccountCreationManager.spec.ts
- packages/user-management/spec/it/standard-user-workflow/core/account/StandardAccountConfirmation.spec.ts
- packages/user-management/spec/ut/standard-user-workflow/core/authentication/LoginPasswordAuthenticationManager.spec.ts
- packages/user-management/spec/ut/standard-user-workflow/legacy/LegacyAdapterUserRepository.spec.ts
- packages/user-management/src/standard-user-workflow/legacy/UserLegacyAdapter.ts
```
[X] Bugfix
[ ] Feature
```
The account status was in the account fields and the fields was never changed at the confirmation. Only the activation of the account was changed.
The account status is in the dedicated field and is correctly changed when the account is confirmed.
```
[ ] Yes
[x] No
```
If this PR …
> fix(update status) - Fix the user status management and add tests

- packages/cli/src/commands/run.js
```
[x] Bugfix
[ ] Feature
```
Push doesn't work anymore
Push works again
```
[ ] Yes
[x] No
```
> Fix/zeta push/provisioning

- packages/create/createApp.js
Manual tests have been done.
```
[x] Bugfix
[ ] Feature
```
When I create a new project with : npm init @zetapush myApp, a new project is correctly created in the folder named "myApp". But in the "worker" part I can't use the "console.log()" function (TypeScript doesn't recognize it).
I can use the "console.log()" function in my worker.
**Does this PR introduce a breaking …
> Add 'dom' lib in tsconfig.json of generated project

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Issue and PR template are not up to date with new packages
```
[ ] Yes
[x] No
```
> Feature/update GitHub templates

- packages/user-management/samples/standard-user-workflow/package.json
- packages/user-management/src/common/configurer/email/EmailConfigurer.ts
```
[x] Bugfix
[ ] Feature
```
When configuring default standard user workflow with smtp properties, the worker doesn't start indicating that no sender (email or sms) is defined.
Now, the smtp implementation is correctly registered and used
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please …
> Hotfix/user management/autoconf smtp

- packages/user-management/spec/it/common/core/email/SmtpHttpEmailSender.spec.ts
- packages/user-management/src/common/core/email/SmtpEmailSender.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(user management) - Fix smtp email sender

- package-lock.json
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
[x] <root>
```
**Does this PR …
> feat(clean-top-level-dependencies): remove useless top level dependencies

- packages/common/src/environment/env-variables-properties.ts
- packages/common/src/environment/error.ts
- packages/common/src/environment/index.ts
- packages/common/src/environment/json5-properties.ts
- packages/common/src/environment/priorized-properties.ts
- packages/common/src/environment/properties.ts
- packages/common/src/environment/utils.ts
affects: @zetapush/common
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
Common package contains …
> feat(common-circular-dependency): remove circular dependencies on common package

- packages/client/src/client/basic.js
- packages/client/src/client/helper.js
- packages/common/src/worker/di.ts
- packages/core/src/Context.ts
- packages/example/worker/index.ts
- packages/testing/src/worker/test-instance.ts
- packages/worker/src/utils/context.ts
- packages/worker/src/utils/worker-instance.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] <root>
[x] @zetapush/core
[x] @zetapush/testing
[x] @zetapush/worker
```
https://github.com/zetapush/zetapush/issues/165 …
> feat(worker-namespace): update worker namespace implementation

- packages/client/src/utils/types.js
- packages/common/src/utils/types.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
Timeoutify correctly …
> fix(timeoutify): fix timeoutify implementation

- packages/client/index.d.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
Update …
> fix(typings): update createProxyTaskService typings to support namespace

- packages/user-management/samples/standard-user-workflow/.gitignore
- packages/user-management/samples/standard-user-workflow/application.json
- packages/user-management/samples/standard-user-workflow/package.json
- packages/user-management/samples/standard-user-workflow/worker/index.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Improvement of the user management example
```
```
[ ] <root>
```
**What …
> Improve the user management example

- packages/user-management/src/standard-user-workflow/legacy/UserLegacyAdapter.ts
```
[x] Bugfix
[ ] Feature
```
The creation of account with "UserLegacyAdapter" can't set account status
Now we can set the account status when we create an account
```
[ ] Yes
[x] No
```
**Other …
> Fix/user management/create account status

- packages/platform-legacy/src/Aggreg/Aggreg.ts
- packages/platform-legacy/src/CommonTypes.ts
- packages/platform-legacy/src/Game/Game.ts
- packages/platform-legacy/src/Groups/Groups.ts
- packages/platform-legacy/src/Logs/Logs.ts
- packages/platform-legacy/src/Macro/Macro.ts
- packages/platform-legacy/src/Messaging/Messaging.ts
- packages/platform-legacy/src/Notif/Notif.ts
- packages/platform-legacy/src/Queue/Queue.ts
- packages/platform-legacy/src/Queue/QueueTypes.ts
- packages/platform-legacy/src/Rdbms/Rdbms.ts
- packages/platform-legacy/src/Search/Search.ts
- packages/platform-legacy/src/Sendmail/Sendmail.ts
- packages/platform-legacy/src/Simple/Simple.ts
- packages/platform-legacy/src/Simple/SimpleTypes.ts
- packages/platform-legacy/src/Sms_ovh/Sms_ovh.ts
- packages/platform-legacy/src/Template/Template.ts
- packages/platform-legacy/src/Trigger/Trigger.ts
- packages/user-management/src/common/core/email/SmtpEmailSender.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] <root>
[x] @zetapush/platform-legacy
```
Generated code …
> feat(update-platform-legacy): update generated platform legacy classes

- packages/client/index.d.ts
```
[x] Bugfix
[x] Feature
```
```
[ ] <root>
```
Client typins doesn't …
> feat(optionnal-proxy-parameters): update typings to make createProxy* parameters optionnal

- packages/client/src/client/helper.js
- packages/client/src/utils/async.js
```
[ ] Bugfix
[x] Feature
```
```
[ ] <root>
``` …
> feat(update-promisify-implementation): update Timeou.wrap implementatupdate-promisify-implementation

- packages/cli/src/utils/http-server.js
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
All served files are transformed, so it's break non …
> fix(http-server): transform only html files

- packages/user-management/src/standard-user-workflow/core/StandardUserWorkflowAsyncTaskService.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
**Does this PR …
> Add client side implementation of StandardUserWorkflow

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/utils/security.js
- packages/create/createApp.js
affects: @zetapush/cli, @zetapush/create, @zetapush/example
ISSUES CLOSED: #100
```
[x] Bugfix
[x] Feature
```
```
[ ] <root>
[x] @zetapush/create
```
**What is the current behavior?** (You can also …
> feat(update-prompt-implementation): replace prompt-sync by prompts

- packages/cli/src/loader/config.js
ISSUES CLOSED: #185
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
Developer login is not …
> fix(Request developer login if missing in loaded config):

- packages/cli/src/utils/progression.js
- packages/common/src/progression.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] <root>
```
All fragments have a …
> feat(deployment-feedback): Display in terminal feedback about deployed urls

- lerna.json
- package.json
ISSUES CLOSED: #194
```
[x] Bugfix
[ ] Feature
```
```
[x] <root>
```
#194 …
> revert(lerna): downgrade to lerna@2

- packages/cli/src/utils/progression.js
```
[ ] Bugfix
[x] Feature
```
```
[ ] <root>
``` …
> feat(ush-progress-color): update push progress color to support errors

- packages/common/src/worker/provisioning.ts
affects: @zetapush/common
```
[ ] Bugfix
[x] Feature
```
```
[ ] <root>
```
Platform services are …
> feat(forbidden-verbs-all): forbidden all verbs for platforme service

- packages/client/src/client/smart.js
- packages/client/src/utils/session-persistence.js
ISSUES CLOSED: #199
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
``` …
> fix(smart-client-persistence): update appName on persistence data level

- lerna.json
- package-lock.json
```
[ ] Bugfix
[x] Feature
```
```
[x] <root>
```
**Does this PR …
> feat(lerna): update lerna config

- packages/client/package-lock.json
- packages/cometd/package-lock.json
- packages/common/package-lock.json
- packages/core/package-lock.json
- packages/create/package-lock.json
- packages/http-server/package-lock.json
- packages/integration/package-lock.json
- packages/platform-legacy/package-lock.json
- packages/testing/package-lock.json
- packages/troubleshooting/package-lock.json
- packages/user-management/package-lock.json
- packages/user-management/spec/ut/standard-user-workflow/legacy/LegacyAdapterUserRepository.spec.ts
- packages/user-management/src/standard-user-workflow/legacy/UserLegacyAdapter.ts
- packages/worker/package-lock.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] <root>
```
I can't get the userKey from the accountId of a …
> feature(User Management) - Add getUserKey() method from accountId

- packages/client/src/utils/error-handler.js
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
Unhandled promise error when the connection failed …
> fix(Client) - Fix PlatformError

- Jenkinsfile
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[x] <root>
```
**Does this PR …
> fix(ci) Bad copy/paste

- CHANGELOG.md
- packages/cli/package-lock.json
- packages/common/package-lock.json
- packages/common/src/environment/platform-event-context.ts
- packages/common/src/utils/server-registry.ts
- packages/integration/package-lock.json
- packages/testing/package-lock.json
- packages/troubleshooting/package-lock.json
- packages/user-management/package-lock.json
- packages/user-management/src/standard-user-workflow/configurer/defaults.ts
- packages/user-management/src/standard-user-workflow/core/account/confirmation/ConfirmationUrlHttpHandler.ts
- packages/worker/package-lock.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
The confirmation of account in StandardUserWorkflow …
> fix(HttpServer) - Fix the httpserver

- packages/user-management/src/common/api/exception/index.ts
- packages/user-management/src/common/api/index.ts
- packages/user-management/src/standard-user-workflow/api/index.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
In the user-management package, some export was not …
> Fix(StandardUserWorkflow) - Add missing export of interfaces

- packages/cli/src/loader/config.js
- packages/create/createApp.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
- **Fix typo**
```
[ ] <root>
[x] @zetapush/create
```
**Does …
> (fix) - some typo + adding command example after npm init

- packages/cli/src/loader/config.js
```
[ ] Bugfix
[x] Feature
```
```
[ ] <root>
``` …
> feat(config): clean defaults properties from serialization process

- packages/create/createApp.js
affects: @zetapush/create
```
[ ] Bugfix
[x] Feature
```
```
[ ] <root>
[x] @zetapush/create
``` …
> feat(cli): handle missing mandatory arguments

- packages/create/template/typescript/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] <root>
```
**Does this PR …
> fix(typo) => package create => README.md

- packages/client/index.d.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
``` …
> fix(typings): support new ProxyTaskService definition

- packages/user-management/src/standard-user-workflow/api/index.ts
affects: @zetapush/user-management
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
**What is the …
> fix(StandardUserWorkflow): expose API LostPassword

- packages/client/index.d.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
Client parameter is required …
> fix(client) client parameter should be optional

- README.md
- packages/create/createApp.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] <root>
```
**Does this PR …
> fix(cli) typo on @zetapush/create missing mandatory arguments

- packages/client/package-lock.json
- packages/common/package-lock.json
- packages/core/package-lock.json
- packages/example/package-lock.json
- packages/http-server/package-lock.json
- packages/platform-legacy/package-lock.json
- packages/testing/package-lock.json
- packages/troubleshooting/package-lock.json
- packages/user-management/package-lock.json
- packages/worker/package-lock.json
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] <root>
```
**Does this PR …
> chore(npm): bump lockfiles

- packages/user-management/spec/it/standard-user-workflow/core/account/StandardAccountRegistration.spec.ts
- packages/user-management/src/standard-user-workflow/api/LostPassword.ts
- packages/user-management/src/standard-user-workflow/configurer/defaults.ts
- packages/user-management/src/standard-user-workflow/configurer/properties.ts
- packages/user-management/src/standard-user-workflow/core/lost-password/EmailAskResetPasswordManager.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
- Confirmation email was displaying "you" by …
> Fix/standard user workflow/email and password loss

- packages/client/src/client/helper.js
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
``` …
> fix(client): add unimplemented method setResource on ClientHelper

- packages/user-management/src/common/configurer/email/EmailConfigurer.ts
- packages/user-management/src/common/configurer/fields/AnnotationsConfigurer.ts
- packages/user-management/src/common/configurer/fields/FieldsConfigurer.ts
- packages/user-management/src/common/configurer/fields/ScanConfigurer.ts
- packages/user-management/src/standard-user-workflow/configurer/StandardUserWorkflowConfigurer.ts
- packages/user-management/src/standard-user-workflow/configurer/account/AccountCreationManagerConfigurer.ts
- packages/user-management/src/standard-user-workflow/configurer/account/RegistrationConfigurerImpl.ts
- packages/user-management/src/standard-user-workflow/configurer/confirmation/RegistrationConfirmationConfigurer.ts
- packages/user-management/src/standard-user-workflow/configurer/lost-password/AskResetPasswordConfigurerImpl.ts
- packages/user-management/src/standard-user-workflow/configurer/lost-password/LostPasswordConfigurerImpl.ts
- packages/user-management/src/standard-user-workflow/configurer/lost-password/ResetPasswordConfigurerImpl.ts
affects: @zetapush/user-management
```
[x] Bugfix
[ ] Feature
```
```
[ ] <root>
```
**What is the …
> fix(user-management): fix configurer override

- packages/cli/bin/cli.js
- packages/cli/src/helper/handle-promise-rejection.js
```
[ ] Bugfix
[x] Feature
```
```
[ ] <root>
``` …
> feat(cli): handle promise rejection with a warning message
